/**
 */
package hu.bme.mit.gamma.expression.model.provider;

import hu.bme.mit.gamma.expression.model.util.ExpressionModelAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ExpressionModelItemProviderAdapterFactory extends ExpressionModelAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ExpressionModelItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.CommentableElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CommentableElementItemProvider commentableElementItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.CommentableElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCommentableElementAdapter() {
		if (commentableElementItemProvider == null) {
			commentableElementItemProvider = new CommentableElementItemProvider(this);
		}

		return commentableElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.Comment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CommentItemProvider commentItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.Comment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCommentAdapter() {
		if (commentItemProvider == null) {
			commentItemProvider = new CommentItemProvider(this);
		}

		return commentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.ArgumentedElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArgumentedElementItemProvider argumentedElementItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.ArgumentedElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArgumentedElementAdapter() {
		if (argumentedElementItemProvider == null) {
			argumentedElementItemProvider = new ArgumentedElementItemProvider(this);
		}

		return argumentedElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.ExpressionPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExpressionPackageItemProvider expressionPackageItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.ExpressionPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExpressionPackageAdapter() {
		if (expressionPackageItemProvider == null) {
			expressionPackageItemProvider = new ExpressionPackageItemProvider(this);
		}

		return expressionPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.ValueDeclaration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ValueDeclarationItemProvider valueDeclarationItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.ValueDeclaration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createValueDeclarationAdapter() {
		if (valueDeclarationItemProvider == null) {
			valueDeclarationItemProvider = new ValueDeclarationItemProvider(this);
		}

		return valueDeclarationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.FunctionDeclaration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionDeclarationItemProvider functionDeclarationItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.FunctionDeclaration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionDeclarationAdapter() {
		if (functionDeclarationItemProvider == null) {
			functionDeclarationItemProvider = new FunctionDeclarationItemProvider(this);
		}

		return functionDeclarationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.TypeDeclaration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TypeDeclarationItemProvider typeDeclarationItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.TypeDeclaration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTypeDeclarationAdapter() {
		if (typeDeclarationItemProvider == null) {
			typeDeclarationItemProvider = new TypeDeclarationItemProvider(this);
		}

		return typeDeclarationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.VariableDeclaration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VariableDeclarationItemProvider variableDeclarationItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.VariableDeclaration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVariableDeclarationAdapter() {
		if (variableDeclarationItemProvider == null) {
			variableDeclarationItemProvider = new VariableDeclarationItemProvider(this);
		}

		return variableDeclarationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.ConstantDeclaration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConstantDeclarationItemProvider constantDeclarationItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.ConstantDeclaration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConstantDeclarationAdapter() {
		if (constantDeclarationItemProvider == null) {
			constantDeclarationItemProvider = new ConstantDeclarationItemProvider(this);
		}

		return constantDeclarationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.ParameterDeclaration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParameterDeclarationItemProvider parameterDeclarationItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.ParameterDeclaration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParameterDeclarationAdapter() {
		if (parameterDeclarationItemProvider == null) {
			parameterDeclarationItemProvider = new ParameterDeclarationItemProvider(this);
		}

		return parameterDeclarationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.FieldDeclaration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FieldDeclarationItemProvider fieldDeclarationItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.FieldDeclaration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFieldDeclarationAdapter() {
		if (fieldDeclarationItemProvider == null) {
			fieldDeclarationItemProvider = new FieldDeclarationItemProvider(this);
		}

		return fieldDeclarationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.LambdaDeclaration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LambdaDeclarationItemProvider lambdaDeclarationItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.LambdaDeclaration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLambdaDeclarationAdapter() {
		if (lambdaDeclarationItemProvider == null) {
			lambdaDeclarationItemProvider = new LambdaDeclarationItemProvider(this);
		}

		return lambdaDeclarationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.Type} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TypeItemProvider typeItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.Type}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTypeAdapter() {
		if (typeItemProvider == null) {
			typeItemProvider = new TypeItemProvider(this);
		}

		return typeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.TypeReference} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TypeReferenceItemProvider typeReferenceItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.TypeReference}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTypeReferenceAdapter() {
		if (typeReferenceItemProvider == null) {
			typeReferenceItemProvider = new TypeReferenceItemProvider(this);
		}

		return typeReferenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.TypeDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TypeDefinitionItemProvider typeDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.TypeDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTypeDefinitionAdapter() {
		if (typeDefinitionItemProvider == null) {
			typeDefinitionItemProvider = new TypeDefinitionItemProvider(this);
		}

		return typeDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.NumericalTypeDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NumericalTypeDefinitionItemProvider numericalTypeDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.NumericalTypeDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNumericalTypeDefinitionAdapter() {
		if (numericalTypeDefinitionItemProvider == null) {
			numericalTypeDefinitionItemProvider = new NumericalTypeDefinitionItemProvider(this);
		}

		return numericalTypeDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.CompositeTypeDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompositeTypeDefinitionItemProvider compositeTypeDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.CompositeTypeDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompositeTypeDefinitionAdapter() {
		if (compositeTypeDefinitionItemProvider == null) {
			compositeTypeDefinitionItemProvider = new CompositeTypeDefinitionItemProvider(this);
		}

		return compositeTypeDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.VoidTypeDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VoidTypeDefinitionItemProvider voidTypeDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.VoidTypeDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVoidTypeDefinitionAdapter() {
		if (voidTypeDefinitionItemProvider == null) {
			voidTypeDefinitionItemProvider = new VoidTypeDefinitionItemProvider(this);
		}

		return voidTypeDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.BooleanTypeDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BooleanTypeDefinitionItemProvider booleanTypeDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.BooleanTypeDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBooleanTypeDefinitionAdapter() {
		if (booleanTypeDefinitionItemProvider == null) {
			booleanTypeDefinitionItemProvider = new BooleanTypeDefinitionItemProvider(this);
		}

		return booleanTypeDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.IntegerTypeDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IntegerTypeDefinitionItemProvider integerTypeDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.IntegerTypeDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIntegerTypeDefinitionAdapter() {
		if (integerTypeDefinitionItemProvider == null) {
			integerTypeDefinitionItemProvider = new IntegerTypeDefinitionItemProvider(this);
		}

		return integerTypeDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.RationalTypeDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RationalTypeDefinitionItemProvider rationalTypeDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.RationalTypeDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRationalTypeDefinitionAdapter() {
		if (rationalTypeDefinitionItemProvider == null) {
			rationalTypeDefinitionItemProvider = new RationalTypeDefinitionItemProvider(this);
		}

		return rationalTypeDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.DecimalTypeDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DecimalTypeDefinitionItemProvider decimalTypeDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.DecimalTypeDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDecimalTypeDefinitionAdapter() {
		if (decimalTypeDefinitionItemProvider == null) {
			decimalTypeDefinitionItemProvider = new DecimalTypeDefinitionItemProvider(this);
		}

		return decimalTypeDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.SubrangeTypeDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubrangeTypeDefinitionItemProvider subrangeTypeDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.SubrangeTypeDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubrangeTypeDefinitionAdapter() {
		if (subrangeTypeDefinitionItemProvider == null) {
			subrangeTypeDefinitionItemProvider = new SubrangeTypeDefinitionItemProvider(this);
		}

		return subrangeTypeDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.EnumerationTypeDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumerationTypeDefinitionItemProvider enumerationTypeDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.EnumerationTypeDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnumerationTypeDefinitionAdapter() {
		if (enumerationTypeDefinitionItemProvider == null) {
			enumerationTypeDefinitionItemProvider = new EnumerationTypeDefinitionItemProvider(this);
		}

		return enumerationTypeDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.EnumerationLiteralDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumerationLiteralDefinitionItemProvider enumerationLiteralDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.EnumerationLiteralDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnumerationLiteralDefinitionAdapter() {
		if (enumerationLiteralDefinitionItemProvider == null) {
			enumerationLiteralDefinitionItemProvider = new EnumerationLiteralDefinitionItemProvider(this);
		}

		return enumerationLiteralDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.ArrayTypeDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArrayTypeDefinitionItemProvider arrayTypeDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.ArrayTypeDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArrayTypeDefinitionAdapter() {
		if (arrayTypeDefinitionItemProvider == null) {
			arrayTypeDefinitionItemProvider = new ArrayTypeDefinitionItemProvider(this);
		}

		return arrayTypeDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.IntegerRangeTypeDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IntegerRangeTypeDefinitionItemProvider integerRangeTypeDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.IntegerRangeTypeDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIntegerRangeTypeDefinitionAdapter() {
		if (integerRangeTypeDefinitionItemProvider == null) {
			integerRangeTypeDefinitionItemProvider = new IntegerRangeTypeDefinitionItemProvider(this);
		}

		return integerRangeTypeDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.FunctionTypeDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionTypeDefinitionItemProvider functionTypeDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.FunctionTypeDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionTypeDefinitionAdapter() {
		if (functionTypeDefinitionItemProvider == null) {
			functionTypeDefinitionItemProvider = new FunctionTypeDefinitionItemProvider(this);
		}

		return functionTypeDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.RecordTypeDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RecordTypeDefinitionItemProvider recordTypeDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.RecordTypeDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRecordTypeDefinitionAdapter() {
		if (recordTypeDefinitionItemProvider == null) {
			recordTypeDefinitionItemProvider = new RecordTypeDefinitionItemProvider(this);
		}

		return recordTypeDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.BasicConstraintDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BasicConstraintDefinitionItemProvider basicConstraintDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.BasicConstraintDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBasicConstraintDefinitionAdapter() {
		if (basicConstraintDefinitionItemProvider == null) {
			basicConstraintDefinitionItemProvider = new BasicConstraintDefinitionItemProvider(this);
		}

		return basicConstraintDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.LogicExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LogicExpressionItemProvider logicExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.LogicExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLogicExpressionAdapter() {
		if (logicExpressionItemProvider == null) {
			logicExpressionItemProvider = new LogicExpressionItemProvider(this);
		}

		return logicExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.OpaqueExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OpaqueExpressionItemProvider opaqueExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.OpaqueExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOpaqueExpressionAdapter() {
		if (opaqueExpressionItemProvider == null) {
			opaqueExpressionItemProvider = new OpaqueExpressionItemProvider(this);
		}

		return opaqueExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.ElseExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ElseExpressionItemProvider elseExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.ElseExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createElseExpressionAdapter() {
		if (elseExpressionItemProvider == null) {
			elseExpressionItemProvider = new ElseExpressionItemProvider(this);
		}

		return elseExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.DefaultExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DefaultExpressionItemProvider defaultExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.DefaultExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDefaultExpressionAdapter() {
		if (defaultExpressionItemProvider == null) {
			defaultExpressionItemProvider = new DefaultExpressionItemProvider(this);
		}

		return defaultExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.IntegerLiteralExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IntegerLiteralExpressionItemProvider integerLiteralExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.IntegerLiteralExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIntegerLiteralExpressionAdapter() {
		if (integerLiteralExpressionItemProvider == null) {
			integerLiteralExpressionItemProvider = new IntegerLiteralExpressionItemProvider(this);
		}

		return integerLiteralExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.DecimalLiteralExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DecimalLiteralExpressionItemProvider decimalLiteralExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.DecimalLiteralExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDecimalLiteralExpressionAdapter() {
		if (decimalLiteralExpressionItemProvider == null) {
			decimalLiteralExpressionItemProvider = new DecimalLiteralExpressionItemProvider(this);
		}

		return decimalLiteralExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.RationalLiteralExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RationalLiteralExpressionItemProvider rationalLiteralExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.RationalLiteralExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRationalLiteralExpressionAdapter() {
		if (rationalLiteralExpressionItemProvider == null) {
			rationalLiteralExpressionItemProvider = new RationalLiteralExpressionItemProvider(this);
		}

		return rationalLiteralExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.TrueExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TrueExpressionItemProvider trueExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.TrueExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTrueExpressionAdapter() {
		if (trueExpressionItemProvider == null) {
			trueExpressionItemProvider = new TrueExpressionItemProvider(this);
		}

		return trueExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.FalseExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FalseExpressionItemProvider falseExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.FalseExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFalseExpressionAdapter() {
		if (falseExpressionItemProvider == null) {
			falseExpressionItemProvider = new FalseExpressionItemProvider(this);
		}

		return falseExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.ArrayLiteralExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArrayLiteralExpressionItemProvider arrayLiteralExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.ArrayLiteralExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArrayLiteralExpressionAdapter() {
		if (arrayLiteralExpressionItemProvider == null) {
			arrayLiteralExpressionItemProvider = new ArrayLiteralExpressionItemProvider(this);
		}

		return arrayLiteralExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.IntegerRangeLiteralExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IntegerRangeLiteralExpressionItemProvider integerRangeLiteralExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.IntegerRangeLiteralExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIntegerRangeLiteralExpressionAdapter() {
		if (integerRangeLiteralExpressionItemProvider == null) {
			integerRangeLiteralExpressionItemProvider = new IntegerRangeLiteralExpressionItemProvider(this);
		}

		return integerRangeLiteralExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.RecordLiteralExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RecordLiteralExpressionItemProvider recordLiteralExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.RecordLiteralExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRecordLiteralExpressionAdapter() {
		if (recordLiteralExpressionItemProvider == null) {
			recordLiteralExpressionItemProvider = new RecordLiteralExpressionItemProvider(this);
		}

		return recordLiteralExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.EnumerationLiteralExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumerationLiteralExpressionItemProvider enumerationLiteralExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.EnumerationLiteralExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnumerationLiteralExpressionAdapter() {
		if (enumerationLiteralExpressionItemProvider == null) {
			enumerationLiteralExpressionItemProvider = new EnumerationLiteralExpressionItemProvider(this);
		}

		return enumerationLiteralExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.FieldAssignment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FieldAssignmentItemProvider fieldAssignmentItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.FieldAssignment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFieldAssignmentAdapter() {
		if (fieldAssignmentItemProvider == null) {
			fieldAssignmentItemProvider = new FieldAssignmentItemProvider(this);
		}

		return fieldAssignmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.ReferenceExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReferenceExpressionItemProvider referenceExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.ReferenceExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReferenceExpressionAdapter() {
		if (referenceExpressionItemProvider == null) {
			referenceExpressionItemProvider = new ReferenceExpressionItemProvider(this);
		}

		return referenceExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.IfThenElseExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IfThenElseExpressionItemProvider ifThenElseExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.IfThenElseExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIfThenElseExpressionAdapter() {
		if (ifThenElseExpressionItemProvider == null) {
			ifThenElseExpressionItemProvider = new IfThenElseExpressionItemProvider(this);
		}

		return ifThenElseExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.NotExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NotExpressionItemProvider notExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.NotExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNotExpressionAdapter() {
		if (notExpressionItemProvider == null) {
			notExpressionItemProvider = new NotExpressionItemProvider(this);
		}

		return notExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.ForallExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ForallExpressionItemProvider forallExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.ForallExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createForallExpressionAdapter() {
		if (forallExpressionItemProvider == null) {
			forallExpressionItemProvider = new ForallExpressionItemProvider(this);
		}

		return forallExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.ExistsExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExistsExpressionItemProvider existsExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.ExistsExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExistsExpressionAdapter() {
		if (existsExpressionItemProvider == null) {
			existsExpressionItemProvider = new ExistsExpressionItemProvider(this);
		}

		return existsExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.ImplyExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImplyExpressionItemProvider implyExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.ImplyExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImplyExpressionAdapter() {
		if (implyExpressionItemProvider == null) {
			implyExpressionItemProvider = new ImplyExpressionItemProvider(this);
		}

		return implyExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.OrExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OrExpressionItemProvider orExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.OrExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOrExpressionAdapter() {
		if (orExpressionItemProvider == null) {
			orExpressionItemProvider = new OrExpressionItemProvider(this);
		}

		return orExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.AndExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AndExpressionItemProvider andExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.AndExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAndExpressionAdapter() {
		if (andExpressionItemProvider == null) {
			andExpressionItemProvider = new AndExpressionItemProvider(this);
		}

		return andExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.XorExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected XorExpressionItemProvider xorExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.XorExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createXorExpressionAdapter() {
		if (xorExpressionItemProvider == null) {
			xorExpressionItemProvider = new XorExpressionItemProvider(this);
		}

		return xorExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.EqualityExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EqualityExpressionItemProvider equalityExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.EqualityExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEqualityExpressionAdapter() {
		if (equalityExpressionItemProvider == null) {
			equalityExpressionItemProvider = new EqualityExpressionItemProvider(this);
		}

		return equalityExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.InequalityExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InequalityExpressionItemProvider inequalityExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.InequalityExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInequalityExpressionAdapter() {
		if (inequalityExpressionItemProvider == null) {
			inequalityExpressionItemProvider = new InequalityExpressionItemProvider(this);
		}

		return inequalityExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.GreaterExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GreaterExpressionItemProvider greaterExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.GreaterExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGreaterExpressionAdapter() {
		if (greaterExpressionItemProvider == null) {
			greaterExpressionItemProvider = new GreaterExpressionItemProvider(this);
		}

		return greaterExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.GreaterEqualExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GreaterEqualExpressionItemProvider greaterEqualExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.GreaterEqualExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGreaterEqualExpressionAdapter() {
		if (greaterEqualExpressionItemProvider == null) {
			greaterEqualExpressionItemProvider = new GreaterEqualExpressionItemProvider(this);
		}

		return greaterEqualExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.LessExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LessExpressionItemProvider lessExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.LessExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLessExpressionAdapter() {
		if (lessExpressionItemProvider == null) {
			lessExpressionItemProvider = new LessExpressionItemProvider(this);
		}

		return lessExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.LessEqualExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LessEqualExpressionItemProvider lessEqualExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.LessEqualExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLessEqualExpressionAdapter() {
		if (lessEqualExpressionItemProvider == null) {
			lessEqualExpressionItemProvider = new LessEqualExpressionItemProvider(this);
		}

		return lessEqualExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.AddExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AddExpressionItemProvider addExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.AddExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAddExpressionAdapter() {
		if (addExpressionItemProvider == null) {
			addExpressionItemProvider = new AddExpressionItemProvider(this);
		}

		return addExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.SubtractExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubtractExpressionItemProvider subtractExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.SubtractExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubtractExpressionAdapter() {
		if (subtractExpressionItemProvider == null) {
			subtractExpressionItemProvider = new SubtractExpressionItemProvider(this);
		}

		return subtractExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.MultiplyExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MultiplyExpressionItemProvider multiplyExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.MultiplyExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMultiplyExpressionAdapter() {
		if (multiplyExpressionItemProvider == null) {
			multiplyExpressionItemProvider = new MultiplyExpressionItemProvider(this);
		}

		return multiplyExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.DivideExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DivideExpressionItemProvider divideExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.DivideExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDivideExpressionAdapter() {
		if (divideExpressionItemProvider == null) {
			divideExpressionItemProvider = new DivideExpressionItemProvider(this);
		}

		return divideExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.DivExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DivExpressionItemProvider divExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.DivExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDivExpressionAdapter() {
		if (divExpressionItemProvider == null) {
			divExpressionItemProvider = new DivExpressionItemProvider(this);
		}

		return divExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.ModExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModExpressionItemProvider modExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.ModExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModExpressionAdapter() {
		if (modExpressionItemProvider == null) {
			modExpressionItemProvider = new ModExpressionItemProvider(this);
		}

		return modExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.UnaryMinusExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnaryMinusExpressionItemProvider unaryMinusExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.UnaryMinusExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUnaryMinusExpressionAdapter() {
		if (unaryMinusExpressionItemProvider == null) {
			unaryMinusExpressionItemProvider = new UnaryMinusExpressionItemProvider(this);
		}

		return unaryMinusExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.UnaryPlusExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnaryPlusExpressionItemProvider unaryPlusExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.UnaryPlusExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUnaryPlusExpressionAdapter() {
		if (unaryPlusExpressionItemProvider == null) {
			unaryPlusExpressionItemProvider = new UnaryPlusExpressionItemProvider(this);
		}

		return unaryPlusExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.FunctionAccessExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionAccessExpressionItemProvider functionAccessExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.FunctionAccessExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionAccessExpressionAdapter() {
		if (functionAccessExpressionItemProvider == null) {
			functionAccessExpressionItemProvider = new FunctionAccessExpressionItemProvider(this);
		}

		return functionAccessExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.ArrayAccessExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArrayAccessExpressionItemProvider arrayAccessExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.ArrayAccessExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArrayAccessExpressionAdapter() {
		if (arrayAccessExpressionItemProvider == null) {
			arrayAccessExpressionItemProvider = new ArrayAccessExpressionItemProvider(this);
		}

		return arrayAccessExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.RecordAccessExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RecordAccessExpressionItemProvider recordAccessExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.RecordAccessExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRecordAccessExpressionAdapter() {
		if (recordAccessExpressionItemProvider == null) {
			recordAccessExpressionItemProvider = new RecordAccessExpressionItemProvider(this);
		}

		return recordAccessExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.bme.mit.gamma.expression.model.SelectExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SelectExpressionItemProvider selectExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hu.bme.mit.gamma.expression.model.SelectExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSelectExpressionAdapter() {
		if (selectExpressionItemProvider == null) {
			selectExpressionItemProvider = new SelectExpressionItemProvider(this);
		}

		return selectExpressionItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (commentableElementItemProvider != null) commentableElementItemProvider.dispose();
		if (commentItemProvider != null) commentItemProvider.dispose();
		if (argumentedElementItemProvider != null) argumentedElementItemProvider.dispose();
		if (expressionPackageItemProvider != null) expressionPackageItemProvider.dispose();
		if (valueDeclarationItemProvider != null) valueDeclarationItemProvider.dispose();
		if (functionDeclarationItemProvider != null) functionDeclarationItemProvider.dispose();
		if (typeDeclarationItemProvider != null) typeDeclarationItemProvider.dispose();
		if (variableDeclarationItemProvider != null) variableDeclarationItemProvider.dispose();
		if (constantDeclarationItemProvider != null) constantDeclarationItemProvider.dispose();
		if (parameterDeclarationItemProvider != null) parameterDeclarationItemProvider.dispose();
		if (fieldDeclarationItemProvider != null) fieldDeclarationItemProvider.dispose();
		if (lambdaDeclarationItemProvider != null) lambdaDeclarationItemProvider.dispose();
		if (typeItemProvider != null) typeItemProvider.dispose();
		if (typeReferenceItemProvider != null) typeReferenceItemProvider.dispose();
		if (typeDefinitionItemProvider != null) typeDefinitionItemProvider.dispose();
		if (numericalTypeDefinitionItemProvider != null) numericalTypeDefinitionItemProvider.dispose();
		if (compositeTypeDefinitionItemProvider != null) compositeTypeDefinitionItemProvider.dispose();
		if (voidTypeDefinitionItemProvider != null) voidTypeDefinitionItemProvider.dispose();
		if (booleanTypeDefinitionItemProvider != null) booleanTypeDefinitionItemProvider.dispose();
		if (integerTypeDefinitionItemProvider != null) integerTypeDefinitionItemProvider.dispose();
		if (rationalTypeDefinitionItemProvider != null) rationalTypeDefinitionItemProvider.dispose();
		if (decimalTypeDefinitionItemProvider != null) decimalTypeDefinitionItemProvider.dispose();
		if (subrangeTypeDefinitionItemProvider != null) subrangeTypeDefinitionItemProvider.dispose();
		if (enumerationTypeDefinitionItemProvider != null) enumerationTypeDefinitionItemProvider.dispose();
		if (enumerationLiteralDefinitionItemProvider != null) enumerationLiteralDefinitionItemProvider.dispose();
		if (arrayTypeDefinitionItemProvider != null) arrayTypeDefinitionItemProvider.dispose();
		if (integerRangeTypeDefinitionItemProvider != null) integerRangeTypeDefinitionItemProvider.dispose();
		if (functionTypeDefinitionItemProvider != null) functionTypeDefinitionItemProvider.dispose();
		if (recordTypeDefinitionItemProvider != null) recordTypeDefinitionItemProvider.dispose();
		if (basicConstraintDefinitionItemProvider != null) basicConstraintDefinitionItemProvider.dispose();
		if (logicExpressionItemProvider != null) logicExpressionItemProvider.dispose();
		if (opaqueExpressionItemProvider != null) opaqueExpressionItemProvider.dispose();
		if (elseExpressionItemProvider != null) elseExpressionItemProvider.dispose();
		if (defaultExpressionItemProvider != null) defaultExpressionItemProvider.dispose();
		if (integerLiteralExpressionItemProvider != null) integerLiteralExpressionItemProvider.dispose();
		if (decimalLiteralExpressionItemProvider != null) decimalLiteralExpressionItemProvider.dispose();
		if (rationalLiteralExpressionItemProvider != null) rationalLiteralExpressionItemProvider.dispose();
		if (trueExpressionItemProvider != null) trueExpressionItemProvider.dispose();
		if (falseExpressionItemProvider != null) falseExpressionItemProvider.dispose();
		if (arrayLiteralExpressionItemProvider != null) arrayLiteralExpressionItemProvider.dispose();
		if (integerRangeLiteralExpressionItemProvider != null) integerRangeLiteralExpressionItemProvider.dispose();
		if (recordLiteralExpressionItemProvider != null) recordLiteralExpressionItemProvider.dispose();
		if (enumerationLiteralExpressionItemProvider != null) enumerationLiteralExpressionItemProvider.dispose();
		if (fieldAssignmentItemProvider != null) fieldAssignmentItemProvider.dispose();
		if (referenceExpressionItemProvider != null) referenceExpressionItemProvider.dispose();
		if (ifThenElseExpressionItemProvider != null) ifThenElseExpressionItemProvider.dispose();
		if (notExpressionItemProvider != null) notExpressionItemProvider.dispose();
		if (forallExpressionItemProvider != null) forallExpressionItemProvider.dispose();
		if (existsExpressionItemProvider != null) existsExpressionItemProvider.dispose();
		if (implyExpressionItemProvider != null) implyExpressionItemProvider.dispose();
		if (orExpressionItemProvider != null) orExpressionItemProvider.dispose();
		if (andExpressionItemProvider != null) andExpressionItemProvider.dispose();
		if (xorExpressionItemProvider != null) xorExpressionItemProvider.dispose();
		if (equalityExpressionItemProvider != null) equalityExpressionItemProvider.dispose();
		if (inequalityExpressionItemProvider != null) inequalityExpressionItemProvider.dispose();
		if (greaterExpressionItemProvider != null) greaterExpressionItemProvider.dispose();
		if (greaterEqualExpressionItemProvider != null) greaterEqualExpressionItemProvider.dispose();
		if (lessExpressionItemProvider != null) lessExpressionItemProvider.dispose();
		if (lessEqualExpressionItemProvider != null) lessEqualExpressionItemProvider.dispose();
		if (addExpressionItemProvider != null) addExpressionItemProvider.dispose();
		if (subtractExpressionItemProvider != null) subtractExpressionItemProvider.dispose();
		if (multiplyExpressionItemProvider != null) multiplyExpressionItemProvider.dispose();
		if (divideExpressionItemProvider != null) divideExpressionItemProvider.dispose();
		if (divExpressionItemProvider != null) divExpressionItemProvider.dispose();
		if (modExpressionItemProvider != null) modExpressionItemProvider.dispose();
		if (unaryMinusExpressionItemProvider != null) unaryMinusExpressionItemProvider.dispose();
		if (unaryPlusExpressionItemProvider != null) unaryPlusExpressionItemProvider.dispose();
		if (functionAccessExpressionItemProvider != null) functionAccessExpressionItemProvider.dispose();
		if (arrayAccessExpressionItemProvider != null) arrayAccessExpressionItemProvider.dispose();
		if (recordAccessExpressionItemProvider != null) recordAccessExpressionItemProvider.dispose();
		if (selectExpressionItemProvider != null) selectExpressionItemProvider.dispose();
	}

}
